package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var (
	initForce  bool
	initProj   string
	initDir    string
	initUser   string
	initServer string
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Write .anamnesia.toml at the current project root",
	Long: "Detect the project slug from the git remote (or directory name) and\n" +
		"write .anamnesia.toml so future runs of `anamnesia hook ...` always\n" +
		"resolve the same project name. Idempotent; --force overwrites.",
	RunE: runInit,
}

func init() {
	initCmd.Flags().BoolVar(&initForce, "force", false, "overwrite an existing .anamnesia.toml")
	initCmd.Flags().StringVar(&initProj, "project", "", "override the project slug")
	initCmd.Flags().StringVar(&initUser, "user", "", "default user handle for this project")
	initCmd.Flags().StringVar(&initServer, "server", "", "override server URL for this project")
	initCmd.Flags().StringVar(&initDir, "dir", "", "directory to write into (default: git toplevel or CWD)")
}

func runInit(cmd *cobra.Command, _ []string) error {
	dir := initDir
	if dir == "" {
		wd, err := os.Getwd()
		if err != nil {
			return err
		}
		dir = gitToplevelOrCWD(wd)
	}
	if _, err := os.Stat(dir); err != nil {
		return fmt.Errorf("dir %s: %w", dir, err)
	}
	path := filepath.Join(dir, ".anamnesia.toml")
	if _, err := os.Stat(path); err == nil && !initForce {
		return fmt.Errorf("%s already exists (use --force to overwrite)", path)
	} else if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}

	proj := initProj
	if proj == "" {
		proj = sanitizeSlug(filepath.Base(dir))
	}
	if proj == "" {
		return errors.New("could not derive a project slug; pass --project")
	}

	var sb []byte
	sb = appendLine(sb, "# Anamnesia per-project configuration.")
	sb = appendLine(sb, "# Generated by `anamnesia init`.")
	sb = appendLine(sb, "")
	sb = appendLine(sb, fmt.Sprintf("project = %q", proj))
	if initUser != "" {
		sb = appendLine(sb, fmt.Sprintf("user = %q", initUser))
	}
	if initServer != "" {
		sb = appendLine(sb, fmt.Sprintf("server = %q", initServer))
	}

	if err := os.WriteFile(path, sb, 0o644); err != nil {
		return err
	}
	fmt.Fprintf(cmd.OutOrStdout(), "✦ wrote %s (project: %s)\n", path, proj)
	return nil
}

func appendLine(b []byte, s string) []byte { return append(b, append([]byte(s), '\n')...) }
